(() => {
  const $ = id => document.getElementById(id), KEY = "guia-objectives-v2";
  let model = normalize(loadLocal() || window.OBJECTIVES_TEMPLATE), wired = false;
  function clone(v){return JSON.parse(JSON.stringify(v));}
  function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]);}
  function num(v){const n=Number(v);return Number.isFinite(n)&&n>=0?Math.round(n):0;}
  function normalize(source){const d=clone(source||window.OBJECTIVES_TEMPLATE);d.store||={ceco:"",name:""};d.values||={};d.days.forEach(day=>{d.values[day.id]||={};d.products.forEach(p=>{d.values[day.id][p.id]||={goal:0,actual:0};});});return d;}
  function loadLocal(){try{return JSON.parse(localStorage.getItem(KEY));}catch{return null;}}
  function save(){localStorage.setItem(KEY,JSON.stringify(model));}
  function total(id,field){return model.days.reduce((s,d)=>s+num(model.values[d.id][id][field]),0);}
  function pct(actual,goal){return goal?Math.round(actual/goal*100):0;}
  function stamp(){return new Intl.DateTimeFormat("es-MX",{dateStyle:"long",timeStyle:"short",timeZone:model.campaign.timezone}).format(new Date());}
  function safeStore(){return (model.store.name.trim()||"Tienda").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/gi,"_").replace(/^_|_$/g,"");}
  function reportFileName(){return `${safeStore()}_Unicorn_Frapp_Cake_Pop`;}
  function status(a,g){const p=pct(a,g);return !a?"Pendiente":p>=100?"Meta lograda":"En avance";}
  function summary(){return model.products.map(p=>{const g=total(p.id,"goal"),a=total(p.id,"actual"),x=pct(a,g);return `<article style="--accent:${p.accent}"><img src="${esc(p.image)}" alt=""><div><small>${esc(p.note)}</small><h2>${esc(p.name)}</h2><div class="summary-metrics"><span><b>${g}</b>Meta</span><span><b>${a}</b>Real</span><span><b>${x}%</b>Avance</span></div><div class="goal-bar"><i style="width:${Math.min(x,100)}%"></i></div></div></article>`;}).join("");}
  function days(){return model.days.map((d,i)=>`<section class="objective-day" id="objective-${d.id}"><header><span>${i+1}</span><div><small>${i===0?"ANTICIPA":"ACTUALIZA"}</small><h2>${esc(d.label)}</h2></div><strong>${model.products.every(p=>num(model.values[d.id][p.id].goal)>0)?"Listo para medir":"Define tus metas"}</strong></header><div class="day-products">${model.products.map(p=>{const v=model.values[d.id][p.id],g=num(v.goal),a=num(v.actual),x=pct(a,g);return `<article><div class="day-product-name"><img src="${esc(p.image)}" alt=""><i style="background:${p.accent}"></i><b>${esc(p.name)}</b></div><label><span>Meta del día</span><input aria-label="Meta ${esc(p.name)} ${esc(d.label)}" type="number" min="0" inputmode="numeric" value="${g||""}" placeholder="0" data-day="${d.id}" data-product="${p.id}" data-field="goal"></label><label><span>Venta real</span><input aria-label="Real ${esc(p.name)} ${esc(d.label)}" type="number" min="0" inputmode="numeric" value="${a||""}" placeholder="0" data-day="${d.id}" data-product="${p.id}" data-field="actual"></label><div class="day-progress"><b>${x}%</b><small>${status(a,g)}</small></div></article>`;}).join("")}</div></section>`).join("");}
  function jump(){return model.days.map((d,i)=>{const ready=model.products.every(p=>num(model.values[d.id][p.id].goal)>0);return `<button type="button" data-target="objective-${d.id}"><span>${ready?"✓":i+1}</span><b>${d.label.split(" de ")[0]}</b><small>${ready?"Meta definida":"Por preparar"}</small></button>`;}).join("");}
  function render(){if(!$("objectiveDays"))return;$("objectiveStore").value=model.store.name||"";$("objectiveSummary").innerHTML=summary();$("objectiveDayJump").innerHTML=jump();$("objectiveDays").innerHTML=days();$("objectiveDayJump").querySelectorAll("button").forEach(button=>button.onclick=()=>document.getElementById(button.dataset.target).scrollIntoView({behavior:"smooth",block:"start"}));$("objectiveDays").querySelectorAll("input").forEach(input=>input.addEventListener("change",e=>{const {day,product,field}=e.currentTarget.dataset;model.values[day][product][field]=num(e.currentTarget.value);save();render();}));}
  function report(){const heads=model.days.map(d=>`<th colspan="3">${esc(d.label)}</th>`).join(""),subs=model.days.map(()=>"<th>Meta</th><th>Real</th><th>Avance</th>").join("");const rows=model.products.map(p=>`<tr><th><span style="color:${p.accent}">${esc(p.name)}</span><small>${esc(p.note)}</small></th>${model.days.map(d=>{const v=model.values[d.id][p.id],g=num(v.goal),a=num(v.actual);return `<td>${g}</td><td>${a}</td><td>${pct(a,g)}%</td>`;}).join("")}<td>${total(p.id,"goal")}</td><td>${total(p.id,"actual")}</td><td>${pct(total(p.id,"actual"),total(p.id,"goal"))}%</td></tr>`).join("");return `<div class="print-cover"><span>JUNTÉMONOS MÁS · PREPARÉMONOS MÁS</span><h1>Objetivos y avance</h1><p>15, 16 y 17 de agosto</p><div><b>${esc(model.store.name)}</b><small>Voz de Operaciones · ${esc(model.campaign.operationsUpdate||"14 de agosto de 2026")} · Exportado ${esc(stamp())}</small></div></div><div class="print-summary">${summary()}</div><table><thead><tr><th rowspan="2">Producto</th>${heads}<th colspan="3">Total</th></tr><tr>${subs}<th>Meta</th><th>Real</th><th>Avance</th></tr></thead><tbody>${rows}</tbody></table><footer>Diseñado: Jorge Alcantar Aguiar &amp; Enrique César Flores</footer>`;}
  function printReport(){if(!model.store.name.trim()){$("objectiveStore").focus();alert("Escribe el nombre de la tienda.");return;}$("objectivePrintReport").innerHTML=report();document.body.classList.add("printing-objectives");const originalTitle=document.title;document.title=reportFileName();const done=()=>{document.body.classList.remove("printing-objectives");document.title=originalTitle;};window.addEventListener("afterprint",done,{once:true});window.print();setTimeout(done,2000);}
  function wire(){if(wired)return;wired=true;$("objectiveStore").addEventListener("input",e=>{model.store.name=e.target.value.trim();save();});$("printObjectives").onclick=printReport;}
  window.Objectives={render(){wire();render();}};
})();
